version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-sq15
    environment:
      POSTGRES_USER: sq15
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: curso_sq15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sq15 -d curso_sq15"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: authapi-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/curso_sq15
      SPRING_DATASOURCE_USERNAME: sq15
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"

volumes:
  postgres_data:
